[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.setup-python]
command = "poetry"
args = ["install","-C","./test_gen"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean","setup-python"]

[tasks.test-test-gen]
command = "poetry"
args = ["run","-C","./test_gen","pytest"]

[tasks.test-gen]
command = "poetry"
args = ["run", "-C","./test_gen","python","./test_gen/convert.py"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean","test-test-gen","test-gen"]

[tasks.test-noisy]
command = "cargo"
args = ["test","--", "--nocapture"]
dependencies = ["build","test-test-gen","test-gen"]

[tasks.my-flow]
dependencies = [
    "format",
    "build",
    "test"
]
